### PR TITLE
Enforce MFA for ALL ldap users

### PR DESCRIPTION
**Pull request by gdestuynder**
This REMOVES the `okta_mfa` group requirement to use Duo MFA on Auth0. Effectively this enforces Duo MFA when using Auth0 for ALL ldap user without any exception.

Should we audit which users are impacted and count them or are we just ok with that?
We can also instead send them to a page that say "create a GitHub account instead, your LDAP won't work anymore for this". Could be a "big" deal requiring comms.

(CC @jeffbryner @hmitsch because FYI/we forgot about that)

### CODE REVIEW

**Comment by jeffbryner** [comment]
Doesn't sound like it will change anything for folks, but I agree a quick audit/count of who would be affected is a good idea.

**Comment by hmitsch** [comment]
Will this break Viorela's test automation accounts?

**Comment by gdestuynder** [comment]
@hmitsch no, @viorelaioia 's testing already uses MFA

**Comment by gdestuynder** [comment]
can I reviews? @jdow

**Comment by gdestuynder** [comment]
@hmitsch this blocks work until we have a decision

**Comment by jeffbryner** [comment]
It's not clear to me what would be different for folks (except they need to setup MFA if they haven't) so it is that straightforward then; yes we should require MFA for all. 

Then the remaining issue is change management, for which it would help to know how many people are affected. Can we determine that?

**Comment by gdestuynder** [comment]
last we checked, about 140 people, we have a list

**Comment by hmitsch** [comment]
Inquiring with kang via direct message to get a more thorough understanding of the situation.

**Comment by andrewkrug** [comment]
@gdestuynder @jeffbryner do we know what's blocking this at this point?  Is it filing the CAB or does it just need code review?

**Comment by gdestuynder** [comment]
@andrewkrug code review would be a good start ! ;-) (really thats what blocking it, please do review :)

**Comment by andrewkrug** [comment]
@gdestuynder this looks simple enough.  Let's go ahead and move forward with deploying this.

**Pull request merged**
