### PR TITLE
Fix unsigned commits in branch master

### PR DESCRIPTION
**Pull request by floatingatoll**
Due to an unsigned commit in the history, I need to rewrite and sign three commits in order to repair things. I have noted in each commit where I was not previously the author that I've done so, and the third commit is my own so no authorship note is included there.

This pull request **must not be merged**, but instead must be **force pushed** onto master. This is a **history rewrite** event.

The following commits will have their authorship changed as a result of this:

0fa187f (gene1wood) -> 2657641 (floatingatoll)
996c70e (rtucker-mozilla) -> f826448 (floatingatoll)

The following merge commit will be removed as it's not possible to reconstruct it with the history rewrite:

f724fbe (floatingatoll) -> [removed]

The following commit has been resigned, but I was already the author of it:

11ddfab (floatingatoll) -> b189d15 (floatingatoll)

### CODE REVIEW

**Comment by gene1wood** [comment]
Weird. I don't have the capability to make unsigned commits so it looks like commit 0fa187fa7bd7b4d5a24eb59da56bab1721208052 was authored by me and committed by floatingatoll 8 days later

```
Commit 0fa187fa
by Gene Wood, 08/02/2021 04:26 PM
committed by floatingatoll, 08/10/2021
```

without a signature. This likely relates to this PR that got closed and committed separately : https://github.com/mozilla-iam/auth0-deploy/pull/378#issuecomment-897915374

**Comment by floatingatoll** [comment]
Yes, that's correct; the PR was an unsigned commit, which I merged using the GitHub website UI, leading to the signed merge commit but the unsigned PR commit within it. This breaks all the things, and so this is cleanup from that event.

@gene1wood If you'd like to do the honors here, you have an org admin account; otherwise I'm planning to work with Alan on it when he's available.

**Comment by duallain** [comment]
I think this should no longer be needed in exactly this form.

**Comment by floatingatoll** [comment]
Fixed by c776152.

**Pull request closed without merging**
