### PR TITLE
Update production branch with current master

### PR DESCRIPTION
**Pull request by The-smooth-operator**
This PR updates the "production" branch with the contents of "master".
Once it is merged, I'll trigger the Codebuild deployment to deploy these changes to production.

At the moment, there are 22 commits to deploy. I'm not confident on deploying those.

### CODE REVIEW

**Comment by gene1wood** [comment]
indeed these are most likely already live in production via manual deploy. Easy way to see is to run a dryrun diff as described here https://github.com/mozilla-iam/auth0-ci#uploader_rulespy
`./uploader_rules.py --dry-run --rules-dir ../auth0-deploy/rules`

The result of that run is
```
$ ./uploader_rules.py --dry-run --rules-dir ../auth0-deploy/rules
[07:47:24] DEBUG [__main__.<module>:81] Got access token for client_id:2t3y42Ads6RTXoWOulizFy0VedhUDQIa
[07:47:24] DEBUG [__main__.<module>:88] Loaded 25 remote rules from current Auth0 deployment
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/temporary-LDAP-re-reintegration.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/temporary-LDAP-re-reintegration.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/SAML-Convercent-Community.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/SAML-Convercent-Community.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/configuration-dumper.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/configuration-dumper.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/AWS-Federated-AMR.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/AWS-Federated-AMR.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/SAML-Braintree-attribute.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/SAML-Braintree-attribute.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/force-ldap-logins-over-ldap.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/force-ldap-logins-over-ldap.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/SAML-configuration-mapping.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/SAML-configuration-mapping.js
[07:47:24] DEBUG [__main__.<module>:169] Difference found in SAML-configuration-mapping :
[07:47:24] DEBUG [__main__.<module>:175] --- auth0-SAML-configuration-mapping[07:47:24] DEBUG [__main__.<module>:175] +++ local-SAML-configuration-mapping[07:47:24] DEBUG [__main__.<module>:175] @@ -3,7 +3,6 @@[07:47:24] DEBUG [__main__.<module>:175]      'wgh8S9GaE7sJ4i0QrAzeMxFXgWZYtB0l': 'sage-intacct',    // Sage Intacct
[07:47:24] DEBUG [__main__.<module>:175]      'R4djNlyXSl3i8N2KXWkfylghDa9kFQ84': 'thinksmart',      // mozilla.tap.thinksmart.com
[07:47:24] DEBUG [__main__.<module>:175]      'cEfnJekrSStxxxBascTjNEDAZVUPAIU2': 'stripe-subplat',  // Stripe - subplat
[07:47:24] DEBUG [__main__.<module>:175] -    'inoLoMyAEOzLX1cZOvubQpcW18pk4O1S': 'acoustic-stage',  // Acoustic stage
[07:47:24] DEBUG [__main__.<module>:175]    };
[07:47:24] DEBUG [__main__.<module>:175]    const client = CLIENTS[context.clientID];
[07:47:24] DEBUG [__main__.<module>:175]  
[07:47:24] DEBUG [__main__.<module>:175] @@ -55,15 +54,6 @@[07:47:24] DEBUG [__main__.<module>:175]          }
[07:47:24] DEBUG [__main__.<module>:175]        });
[07:47:24] DEBUG [__main__.<module>:175]        break;
[07:47:24] DEBUG [__main__.<module>:175] -      case 'acoustic-stage':
[07:47:24] DEBUG [__main__.<module>:175] -      context.samlConfiguration.mappings = {
[07:47:24] DEBUG [__main__.<module>:175] -        'NameId': 'email',
[07:47:24] DEBUG [__main__.<module>:175] -        'email': 'email',
[07:47:24] DEBUG [__main__.<module>:175] -        'firstName': 'given_name',
[07:47:24] DEBUG [__main__.<module>:175] -        'lastName': 'family_name'
[07:47:24] DEBUG [__main__.<module>:175] -      };
[07:47:24] DEBUG [__main__.<module>:175] -
[07:47:24] DEBUG [__main__.<module>:175] -      break;
[07:47:24] DEBUG [__main__.<module>:175]    }
[07:47:24] DEBUG [__main__.<module>:175]  
[07:47:24] DEBUG [__main__.<module>:175]    return callback(null, user, context);
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/duosecurity.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/duosecurity.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/HRIS-is-staff.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/HRIS-is-staff.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/activate-new-users-in-CIS.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/activate-new-users-in-CIS.js
[07:47:24] DEBUG [__main__.<module>:169] Difference found in activate-new-users-in-CIS :
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/Everyone-is-in-the-everyone-group.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/Everyone-is-in-the-everyone-group.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/Global-Function-Declarations.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/Global-Function-Declarations.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/default-deny-for-maintenance.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/default-deny-for-maintenance.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/SAML-gcp-gsuite.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/SAML-gcp-gsuite.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/security-block-ips.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/security-block-ips.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/CIS-Claims-fixups.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/CIS-Claims-fixups.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/AccessRules.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/AccessRules.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/SAML-Navex-partition-id.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/SAML-Navex-partition-id.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/temporary-hrdata.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/temporary-hrdata.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/SAML-lgtm.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/SAML-lgtm.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/temporary-update-at-conformance.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/temporary-update-at-conformance.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/restricted-users.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/restricted-users.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/aai.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/aai.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/link-users-by-email-with-metadata.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/link-users-by-email-with-metadata.js
[07:47:24] DEBUG [__main__.<module>:124] Reading local rule configuration ../auth0-deploy/rules/SAML-test-mozilla-com-google.json
[07:47:24] DEBUG [__main__.<module>:138] Reading local rule code ../auth0-deploy/rules/SAML-test-mozilla-com-google.js
[07:47:24] DEBUG [__main__.<module>:186] Found 25 local rules
[07:47:24] DEBUG [__main__.<module>:194] Found 0 rules that not longer exist locally and will be deleted remotely
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule temporary-LDAP-re-reintegration is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule SAML-Convercent-Community is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule configuration-dumper is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule AWS-Federated-AMR is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule SAML-Braintree-attribute is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule force-ldap-logins-over-ldap is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:227] [~] Dry Run : Action not taken : Updating rule SAML-configuration-mapping (rul_zsufGEmKzhxDI2LU) on Auth0
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule duosecurity is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule HRIS-is-staff is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:227] [~] Dry Run : Action not taken : Updating rule activate-new-users-in-CIS (rul_SIn3HlLdD3CB250l) on Auth0
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule Everyone-is-in-the-everyone-group is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule Global-Function-Declarations is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule default-deny-for-maintenance is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule SAML-gcp-gsuite is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule security-block-ips is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule CIS-Claims-fixups is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule AccessRules is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule SAML-Navex-partition-id is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule temporary-hrdata is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule SAML-lgtm is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule temporary-update-at-conformance is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule restricted-users is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule aai is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule link-users-by-email-with-metadata is unchanged, will not update
[07:47:24] DEBUG [__main__.<module>:224] [=] Rule SAML-test-mozilla-com-google is unchanged, will not update
```

which shows that the only change is the acoustic stage so you're good to proceed

**Review by gene1wood — APPROVED** [review]

**Comment by The-smooth-operator** [comment]
great, thank you!

**Comment by sciurus** [comment]
@gene1wood you were the last one to edit activate-new-users-in-CIS.js. Can you look at the merge conflict?

**Comment by gene1wood** [comment]
Sure, I'll close this in favor of #363

**Pull request closed without merging**
