### PR TITLE
Update alerts colors

### PR DESCRIPTION
**Pull request by comzeradd**
This is based on the new Mozilla brand guidelines

### CODE REVIEW

**Comment by gdestuynder** [comment]
lets hold onto that until this Friday in case things change (see https://www.pivotaltracker.com/story/show/152020211)
Note: we could probably also drop the alert from the lock at this point, I think, since dashboard also has alerts

**Comment by gdestuynder** [comment]
@comzeradd so this actually changed ;-)
I wonder if we should just drop the alert, or wait for the new lock?

**Comment by comzeradd** [comment]
I'd drop that alert from the lock. We are going to drop this alert anyway when F57 is released.
When we have the new lock we can rethink if we want to show alerts there or not.

**Comment by gdestuynder** [comment]
@jeffbryner i can drop the beta alert during the prod cab tomorrow, if we want. need your ack though!

**Comment by jeffbryner** [comment]
I think it's fine to remove it since we have the SSO dashboard alerting.

**Comment by gdestuynder** [comment]
ok, will do!
closing pr

**Pull request closed without merging**
