### PR TITLE
Merge of code already in prod

### PR DESCRIPTION
**Pull request by gdestuynder**
Fix was deployed during change window

### CODE REVIEW

**Comment by gdestuynder** [comment]
FYI - @jdow @tyearns we'll need to talk to Biztera since their RP breaks with namespaced claims (we're good in prod as we tested and fixed during change window)

**Comment by andrewkrug** [comment]
This still floats the button incorrectly at less than 748px.  @comzeradd any thoughts on how we can fix this?

**Comment by gdestuynder** [comment]
i think the intention was that it only fails when you resize but not when you display

**Comment by gdestuynder** [comment]
fixed

**Pull request merged**
