### PR TITLE
Added Google Analytics

### PR DESCRIPTION
**Pull request by hmitsch**
Added GA tag to head

### CODE REVIEW

**Comment by flamingspaz** [comment]
This should be wrapped in DNT code if we're using the regular privacy policy for the hosted lock.

**Comment by hmitsch** [comment]
@flamingspaz, the DNT wrapper was added. Would you agree with this to be merged now?

**Comment by flamingspaz** [comment]
I believe you'll also need to call `WebAnalytics()` to get it to run.

**Comment by gene1wood** [comment]
Please submit this against `master` as use of the `development` branch is pending mozilla-iam/mozilla-iam#9

**Comment by hmitsch** [comment]
Closing, superseded by https://github.com/mozilla-iam/auth0-deploy/pull/68

**Pull request closed without merging**
