### PR TITLE
Add different ikey and skey for login

### PR DESCRIPTION
**Pull request by april**
As well as fix up a lot of code and add more tests.

### CODE REVIEW

**Comment by april** [comment]
cc: @jdow, @rtucker-mozilla, @cshields

To verify that this matches up against their design vision. I've already added the configuration variables to test, so we would simply need to merge the rule change in and it would start working.

**Comment by rtucker-mozilla** [comment]
I  happily defer to your expertise @april

**Comment by april** [comment]
Should we still move forward on this project? If so, I can get this merged provided @gene1wood is able to provide review.

**Review by gene1wood — COMMENTED** [review]
I'm unsure how this fits in with the IAM teams desires here in 2024

**Comment by dividehex** [comment]
This is no longer needed.

**Pull request closed without merging**
